# Generated by Django 4.2.1 on 2023-06-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photocomment',
            options={'ordering': ['-date_time_of_publication']},
        ),
    ]
